/**
 * ElTocardo.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiProviderAiModelDto } from './aiProviderAiModelDto';
import { AiProviderEnumDto } from './aiProviderEnumDto';


export interface AiProviderDto { 
    name: AiProviderEnumDto;
    models: Array<AiProviderAiModelDto>;
}
export namespace AiProviderDto {
}


